routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/helper-datas', 'HomeController@helper_data');

Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile', 'ProfileController@update')->name('profile.update');

Route::prefix('admin')->namespace('Admin')->middleware(['auth'])->group(function() {
    Route::get('files/{file}/download', 'FilesController@download');

    Route::resource('doctors', 'DoctorsController');
    Route::resource('files', 'FilesController');
    Route::resource('hospitals', 'HospitalsController');
    Route::resource('users', 'UsersController');
    Route::resource('indicators', 'IndicatorsController');
});

Route::prefix('doctor')->namespace('Doctor')->middleware(['auth'])->group(function() {
    Route::get('files/{file}/download', 'FilesController@download')->name('doctor.file-download');
    Route::resource('files', 'FilesController', ['as' => 'doctor']);
});

app/Models/Hospital.php
<?php

namespace Healtho\Models;

use Illuminate\Database\Eloquent\Model;

class Hospital extends Model
{
    protected $fillable = [ 'name', 'status' ];
}

app/Http/Controllers/Admin/HospitalsController.php
<?php

namespace Healtho\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Healtho\Http\Controllers\Controller;

use Healtho\Models\Hospital;
use Healtho\Repositories\Interfaces\HospitalRepositoryInterface as HospitalInterface;

class HospitalsController extends Controller
{
    protected $hospitalRepo;

    public function __construct(HospitalInterface $repo)
    {
        $this->middleware('needsRole:admin');
        $this->hospitalRepo = $repo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('toDataTables') && $request->isMethod('GET') ) {
            return response()->json( 
                $this->dtFormat(
                    $this->hospitalRepo->findAll()
                    )
                );
        }
        $hospitals = Hospital::paginate(10);
        return view('admin.hospitals.index', compact('hospitals'));
    }

    public function create() {
        return view('admin.hospitals.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // TODO: Retirar esse processamento daqui.
        $dataValidated = $request->validate([
            'name' => 'bail|required|unique:hospitals|max:255',
            'status' => 'required|boolean',
        ]);

        try {
            $data = $dataValidated;
            $this->hospitalRepo->create( $data );
            return redirect()->route('hospitals.index')->with([
                'status' => 'success',
                'message' => 'Hospital adicionado com sucesso!'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('hospitals.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $hospital = $this->hospitalRepo->find( $id );
            return view('admin.hospitals.edit', compact('hospital'));
        } catch(ModelNotFoundException $e) {
            return redirect()->route('hospitals.index')->with([
                'status' => 'danger',
                'message' => 'Registro inexistente na base de dados.'
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // TODO: Retirar esse processamento daqui.
        $dataValidated = $request->validate([
            'name' => 'bail|required|unique:hospitals|max:255',
            'status' => 'required|boolean',
        ]);

        try {
            $data = $dataValidated;
            $this->hospitalRepo->update($id, $data );
            return redirect()->route('hospitals.index')->with([
                'status' => 'success',
                'message' => 'Hospital editado com sucesso!'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('hospitals.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->hospitalRepo->delete($id);
            return redirect()->route('hospitals.index')->with([
                'status' => 'success',
                'message' => 'Hospital apagado com sucesso!'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('hospitals.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
    }

    /**
     * Formatador de dados para o data tables
     */
    private function dtFormat( $data ) {
        $response = [];
        $response['data'] = [];

        foreach ($data as $item) {
            $item->action_buttons = '<a role="button" class="btn btn-primary btn-xs" href="/admin/hospitals/'.$item->id.'/edit" style="margin-right: 6px"><i class="fa fa-fw fa-edit"></i> editar</a>';
            $item->action_buttons .= '<button type="button" class="btn btn-danger btn-xs"><i class="fa fa-fw fa-trash-o"></i> apagar</button>';

            $response['data'][] = [
                $item->id,
                $item->status ? 'ATIVO': 'INATIVO',
                $item->name,
                $item->action_buttons
            ];
        }

        return $response;
    }
}

resources/views/admin/hospitals/create.blade.php
@extends('layouts.base')

@section('title-header')
    <h2>
        Dashboard Administrivo
        <small>Hospitais</small>
    </h2>
@stop

@section('content')
    <div class="card">
        <div class="header">
            <h2>Formulário de Cadastro de Hospitais</h2>
        </div>
        <div class="body">
            <form action="{{ route('hospitals.store') }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="status" value="1">

                <div class="form-group row">
                    <div class="form-line">
                        <label for="name">Nome do Hospital</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                </div>

                <button type="submit" class="btn btn-raised">Adicionar Registro</button>
                <a role="button" class="btn btn-raised btn-danger " href="{{ route('hospitals.index') }}">Cancelar</a>
            </form>
        </div>
    </div>
@stop

resources/views/admin/hospitals/edit.blade.php
@extends('layouts.base')

@section('title-header')
    <h2>
        Dashboard Administrivo
        <small>Hospitais</small>
    </h2>
@stop

@section('content')
    <div class="card">
        <div class="header">
            <h2>Formulário de Edição de Hospitais</h2>
        </div>
        <div class="body">
            <form action="{{ route('hospitals.update', ['id' => $hospital->id ]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                <input type="hidden" name="status" value="1">
                <div class="form-group row">
                    <div class="form-line">
                        <label for="name">Nome do Hospital</label>
                        <input type="text" class="form-control" id="name" value="{{ $hospital->name }}" name="name">
                    </div>
                </div>

                <button type="submit" class="btn btn-raised">Atualizar Registro</button>
                <a role="button" class="btn btn-raised btn-danger " href="{{ route('hospitals.index') }}">Cancelar</a>
            </form>
        </div>
    </div>
@stop

resources/views/admin/hospitals/index.blade.php
@extends('layouts.base')


@section('block-header')
    <h2>
        Dashboard Administrivo
        <small>Hospitais</small>
    </h2>
@stop

@section('content')
    <div class="card card-default">
        <div class="header">
            <h2>
                <i class="fa fa-fw fa-building-o"></i>
                Hospitais cadastrados no sistema
                <a role="button" 
                    class="btn btn-raised btn-primary btn-sm float-right" 
                    style="margin-top: -1px"
                    href="{{ route('hospitals.create') }}">Adicionar Hospital</a>
            </h2>
        </div>
        <div class="body">
            <div class="table-responsive">
                <table class="table table-sm table-striped">
                    <thead>
                        <th>ID</td>
                        <th>Status</th>
                        <th>Nome</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach( $hospitals as $hospital )
                            <tr>
                                <td>{{ $hospital->id }}</td>
                                <td>{{ $hospital->status ? 'Ativo' : 'Inativo'  }}</td>
                                <td>{{ $hospital->name }}</td>
                                <td class="text-right">
                                    <a role="button" 
                                        class="btn btn-raised btn-default btn-circle waves-effect waves-circle wave-float"
                                        href="{{ route('hospitals.edit', ['id' => $hospital->id]) }}">
                                        <i class="material-icons">edit</i>
                                    </a>
                                    <button type="button" 
                                        class="btn btn-raised btn-danger btn-circle waves-effect waves-circle wave-float"
                                        onclick="deleteHospital({{$hospital->id}})">
                                        <i class="material-icons">delete</i>
                                    </button>
                                    <form id="hospital-{{ $hospital->id }}" action="{{ route('hospitals.destroy', ['id' => $hospital->id]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $hospitals->links("pagination::bootstrap-4") !!}
            </div>
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('js/hospitals.js') }}?{{ date('dmYHis') }}"></script>
@stop