routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/helper-datas', 'HomeController@helper_data');

Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile', 'ProfileController@update')->name('profile.update');

Route::prefix('admin')->namespace('Admin')->middleware(['auth'])->group(function() {
    Route::get('files/{file}/download', 'FilesController@download');

    Route::resource('doctors', 'DoctorsController');
    Route::resource('files', 'FilesController');
    Route::resource('hospitals', 'HospitalsController');
    Route::resource('users', 'UsersController');
    Route::resource('indicators', 'IndicatorsController');
});

Route::prefix('doctor')->namespace('Doctor')->middleware(['auth'])->group(function() {
    Route::get('files/{file}/download', 'FilesController@download')->name('doctor.file-download');
    Route::resource('files', 'FilesController', ['as' => 'doctor']);
});

app/Models/File.php
<?php

namespace Healtho\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    public function owner() {
        return $this->belongsTo(Doctor::class, 'doctor_id');
    }
}

app/Http/Controllers/Admin/FilesController.php
<?php

namespace Healtho\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Healtho\Http\Controllers\Controller;

use Healtho\Models\Doctor;
use Healtho\Models\File;

use Auth;

class FilesController extends Controller
{
    public function __construct()
    {
        $this->middleware('needsRole:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = [];
        $query[] = ['category','!=', 'DOCTOR'];

        /**
         * Filtrando valores baseados nos filtros fornecidos
         */
        if ( $request->input('document_category') ) {
            $query[] = ['category', '=', $request->input('document_category')]; 
        }
        if ( $request->input('doctor') ) {
            $query[] = ['doctor_id', '=', $request->input('doctor')];
        }
        if ( $request->input('document_name') ) {
            $query[] = ['name', 'like', '%'.$request->input('document_name').'%'];
        }

        $doctors = Doctor::all();// usar repositorio!
        $files = File::where($query)->paginate(10);

        return view('admin.files.index', compact('files', 'doctors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $doctors = Doctor::all();// usar repositorio!
        return view('admin.files.create', compact('doctors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $file = $request->file;
            $pfile = new File();
            $pfile->doctor_id = $request->input('owner');
            $pfile->category = $request->input('category');
            $pfile->name = $request->input('name');
            $pname = 'documento-'. date('dmYHis') .'-'. Auth::user()->id .'-'. $pfile->doctor_id .'.'. $file->extension();
            $pfile->path = $file->storeAs('documentos/'.$request->input('category'), $pname);
            $pfile->save();

            return redirect()->route('files.index')->with([
                'status' => 'success',
                'message' => 'Documento adicionado com sucesso!'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('files.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $pfile = File::findOrFail( $id );

            /** deletando arquivos associados do servidor */
            Storage::delete($pfile->path);

            $pfile->delete();
            return redirect()->route('files.index')->with([
                'status' => 'success',
                'message' => 'Documento deletado com sucesso !'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('files.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
    }

    public function download($id)
    {
        $pfile = File::findOrFail( $id );
        return Storage::download($pfile->path);
    }

    /**
     * Formatador de dados para o data tables
     */
    private function dtFormat( $data ) {
        $response = [];
        $response['data'] = [];

        foreach ($data as $item) {
            $item->action_buttons = '<a role="button" target="_blank" class="btn btn-primary btn-xs" href="/admin/files/'.$item->id.'/download" title="download" style="margin-right: 3px"><i class="fa fa-fw fa-download"></i> download</a>';
            $item->action_buttons .= '<button type="button" class="btn btn-danger btn-xs" onclick="deleteFile('.$item->id.')"><i class="fa fa-fw fa-trash" title="apagar"></i> apagar</button>';

            $response['data'][] = [
                $item->id,
                $item->name,
                $item->category,
                $item->owner->name,
                $item->action_buttons
            ];
        }

        return $response;
    }
}

app/Http/Controllers/Doctor/FilesController.php
<?php

namespace Healtho\Http\Controllers\Doctor;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Healtho\Http\Controllers\Controller;

use Healtho\Models\File;

use Auth;

class FilesController extends Controller
{
    public function __construct() {
        $this->middleware('needsRole:doctor');
    }

    public function index() {
        $files = File::where([
            ['category', 'DOCTOR'],
            ['doctor_id', Auth::user()->doctor->id]
        ])->paginate(10);
        return view('doctor.files.index', compact('files'));
    }

    public function create(Request $request) {
        return view('doctor.files.create');
    }

    public function store(Request $request) {
        try {
            $file = $request->file;
            $pfile = new File();
            $pfile->doctor_id = $request->input('owner');
            $pfile->category = $request->input('category');
            $pfile->name = $request->input('name');
            $pname = 'documento-'. date('dmYHis') .'-'. Auth::user()->id .'-'. $pfile->doctor_id .'.'. $file->extension();
            $pfile->path = $file->storeAs('documentos/'.$request->input('category'), $pname);
            $pfile->save();

            return redirect()->route('doctor.files.index')->with([
                'status' => 'success',
                'message' => 'Documento adicionado com sucesso!'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('doctor.files.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
    }

    public function destroy($id) {
        try {
            $pfile = File::findOrFail( $id );

            /** deletando arquivos associados do servidor */
            Storage::delete($pfile->path);

            $pfile->delete();
            return redirect()->route('doctor.files.index')->with([
                'status' => 'success',
                'message' => 'Documento deletado com sucesso !'
            ]);
        } catch(\Exception $e) {
            return redirect()->route('doctor.files.index')->with([
                'status' => 'danger',
                'message' => 'Ocorreu algum erro. Tente novamente.'
            ]);
        }
    }

    public function download($id)
    {
        $pfile = File::findOrFail( $id );
        return Storage::download($pfile->path);
    }
}

resources/views/admin/files/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="card">
        <div class="header">
            <h2>
                <i class="fa fa-fw fa-file-excel-o"></i>
                Formulário de adição de novo arquivo
            </h2>
        </div>
        <div class="body">
            <form action="{{ route('files.store') }}" enctype="multipart/form-data" method="POST">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                <label for="name" >Nome do Arquivo</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="arquivo.pdf">
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group drop-custum focused">
                            <label for="category" >Tipo</label>
                            <select class="form-control" id="category" name="category">
                                <option>Selecione o tipo</option>
                                <option value="DOC">DOC</option>
                                <option value="EXCEL">EXCEL</option>
                                <option value="PDF">PDF</option>
                                <option value="NFE">NFE</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group drop-custum focused">
                            <label for="owner">Médico</label>
                            <select class="form-control" id="owner" name="owner" required>
                                <option>Selecione o Médico</option>
                                @foreach( $doctors as $doctor)
                                    <option value="{{ $doctor->id }}">{{ $doctor->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-lg-12 col-md-12">
                        <div class="form-group float-right">
                            <input type="file" class="form-control-file" id="file" name="file">
                        </div>
                    </div>
                </div>

                <div class="float-right">
                    <button type="submit" class="btn btn-primary btn-raised">
                        Upload
                    </button>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script 
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.js" 
        integrity="sha256-PtzTX1ftmEmj8YUiAX0wTIQ+ddTAGVt2MiLMsGsAMxM=" 
        crossorigin="anonymous"
    ></script>
    <script src="/js/bootstrap-fileselect.js"></script>
    <script>
        $('#file').fileselect({
            language: "en",
            browseBtnClass: 'btn btn-danger btn-raised'
        });
    </script>
@stop

resources/views/admin/files/index.blade.php
@extends('layouts.base')


@section('content')
    <div class="card card-default">
        <div class="header">
            <h2>
                Arquivos Adicionados
                <a role="button" class="btn btn-sm btn-raised btn-primary float-right" href="{{ route('files.create') }}">
                    Adicionar Novo Arquivo
                </a>
            </h2>
        </div>
        <div class="card-body">
            <div class="search-filters"
                style="
                    background-color: #f4f4f4;
                    margin-bottom: 12px;
                    border: 1px solid rgba(0,0,0,.15);
                    border-radius: .25rem;
                "
            >
                <form class="form-inline" method="GET">
                    <label class="mr-sm-2" for="document_category" style="margin-left:12px;">Tipo Documento</label>
                    <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="document_category" name="document_category">
                        <option selected></option>
                        <option value="DOC" @if( Request::input('document_category') == 'DOC' ) selected @endif>DOC</option>
                        <option value="EXCEL" @if( Request::input('document_category') == 'EXCEL' ) selected @endif>EXCEL</option>
                        <option value="PDF" @if( Request::input('document_category') == 'PDF' ) selected @endif>PDF</option>
                        <option value="NFE" @if( Request::input('document_category') == 'NFE' ) selected @endif>NFE</option>
                    </select>

                    <label class="mr-sm-2" for="doctor" style="margin-left:12px;">Médico</label>
                    <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="doctor" name="doctor">
                        <option selected></option>
                        @foreach( $doctors as $doctor)
                            <option value="{{ $doctor->id }}" @if( Request::input('doctor') == $doctor->id ) selected @endif>{{ $doctor->name }}</option>
                        @endforeach
                    </select>
                    
                    <input 
                        type="text" 
                        class="form-control" 
                        id="document_name" 
                        name="document_name"
                        placeholder="Título"
                        style="
                            margin-top: 6px;
                            margin-right: 12px;
                            margin-left: 12px;
                            background-size: 8px 10px;
                            border: 1px solid rgba(0,0,0,.15);
                            border-radius: .25rem;
                            padding: 6px;
                            display: inline-block;
                            max-width: 100%;
                            height: calc(2.25rem + 2px);
                        "
                        value="{{ Request::input('document_name') }}"
                    />
                    
                    <button type="submit" class="btn btn-raised btn-primary">Filtrar</button>
                </form>
            </div>

            <div class="table-responsive">
                <table class="table table-sm table-bordered table-striped">
                    <thead>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Médico</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach($files as $file)
                            <tr>
                                <td>{{ $file->id }}</td>
                                <td>{{ $file->name }}</td>
                                <td>{{ $file->category }}</td>
                                <td>{{  $file->owner ? $file->owner->name : 'não informado' }}</td>
                                <td class="text-right">
                                    <a role="button" target="_blank" class="btn btn-primary btn-xs btn-raised" href="/admin/files/{{$file->id}}/download" title="download">download</a>
                                    <button type="button" class="btn btn-danger btn-xs btn-raised" onclick="deleteFile({{$file->id}})">apagar</button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            
            {!! $files->links("pagination::bootstrap-4") !!}
        </div>
    </div>

    <form id="delete_form" method="post">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
@stop

@section('js')
    <script src="{{ asset('js/files.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.custom-select').select2({
                theme: "bootstrap4"
            });
        });
    </script>
@stop